[package]
name = "ac2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.7"
itertools = "0.11.0"
lib = { path = "./../lib"}
nom = "7.1.3"
pathfinding = "4.3.2"
