[package]
name = "ac2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.10"
lib = { version = "0.1.0", path = "../lib" }
nom = "7.1.3"
