name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo +nightly build
    - name: Test
      run: cargo +nightly test
    - name: Run 2021
      run: cargo +nightly run --bin ac2021
    - name: Run 2022
      run: cargo +nightly run --bin ac2022
